#!/usr/bin/env bash
# Teach nginx the real client IP.
#
# Cloudflare proxies this site, so nginx's $remote_addr is a Cloudflare edge address and every
# rider looks like the same handful of IPs. Downstream that meant one shared rate-limit bucket
# for the entire user base, and — until reports grew their own id — one shared crowd-report
# identity, where the first person to report a bus silenced everyone else for an hour.
#
# The realip module rewrites $remote_addr from CF-Connecting-IP, but *only* for requests that
# actually arrived from a Cloudflare address. The origin IP is public and reachable directly, so
# without that restriction anyone could forge the header and pick their own identity.
#
# Re-run this when Cloudflare publishes new ranges (rarely).
set -euo pipefail

CONF=/etc/nginx/conf.d/cloudflare-realip.conf
TMP=$(mktemp)

{
  echo "# Generated by scripts/nginx-realip.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not edit by hand."
  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    # `|| [ -n "$cidr" ]` because both lists end without a trailing newline, and a plain
    # `while read` silently discards that last line — which cost two real Cloudflare ranges,
    # whose traffic would then keep arriving as an edge address instead of the rider's own.
    curl -fsS --max-time 20 "$url" | while read -r cidr || [ -n "$cidr" ]; do
      [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
    done
  done
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

# A truncated download would silently narrow the trusted set and hand every direct-to-origin
# request the ability to spoof, so refuse to install a file that is obviously short.
GOT=$(grep -c set_real_ip_from "$TMP")
WANT=$(( $(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v4 | grep -c .) \
       + $(curl -fsS --max-time 20 https://www.cloudflare.com/ips-v6 | grep -c .) ))
if [ "$GOT" -lt "$WANT" ] || [ "$GOT" -lt 20 ]; then
  echo "refusing to install: kept $GOT of $WANT published ranges" >&2
  rm -f "$TMP"; exit 1
fi

sudo cp "$TMP" "$CONF"
sudo chmod 644 "$CONF"
rm -f "$TMP"
sudo nginx -t
sudo systemctl reload nginx
echo "installed $CONF ($GOT of $WANT published ranges)"
